# Task T-001: Create Task Model
# Spec: specs/features/task-crud.md § Data Model
# Plan: specs/plan.md § models.py

"""
Data models for the Todo application.

This module defines the core Task model used throughout the application.
"""

from dataclasses import dataclass
from datetime import datetime


@dataclass
class Task:
    """
    Represents a todo task.
    
    A Task contains all information needed to track a single todo item,
    including its unique identifier, title, optional description, completion
    status, and creation timestamp.
    
    Attributes:
        id: Unique task identifier (auto-generated by storage layer)
        title: Task title (required, 1-200 characters)
        description: Optional task description (max 1000 characters)
        completed: Task completion status (default: False)
        created_at: Timestamp when task was created (auto-generated)
    
    Example:
        >>> task = Task(id=1, title="Buy groceries", description="Milk, eggs")
        >>> print(task)
        [1] [ ] Buy groceries
        >>> task.completed = True
        >>> print(task)
        [1] [✓] Buy groceries
    """
    id: int
    title: str
    description: str = ""
    completed: bool = False
    created_at: datetime = None
    
    def __post_init__(self) -> None:
        """
        Initialize created_at timestamp if not provided.
        
        This method is called automatically after __init__ by dataclass.
        If created_at is None, it sets it to the current datetime.
        """
        if self.created_at is None:
            self.created_at = datetime.now()
    
    def __str__(self) -> str:
        """
        Return a human-readable string representation of the task.
        
        Format: [ID] [STATUS] Title
        where STATUS is "✓" for completed tasks and " " for incomplete tasks.
        
        Returns:
            str: Formatted task string for display
        
        Example:
            "[1] [✓] Buy groceries" (completed)
            "[2] [ ] Call mom" (incomplete)
        """
        status = "✓" if self.completed else " "
        return f"[{self.id}] [{status}] {self.title}"